package com.example.climbingtraining.model

enum class DbResultState() {
    NEUTRAL,
    CONFIG_SAVE_SUCCESS,
    CONFIG_SAVE_FAILED,
    CONFIG_EDIT_SUCCESS,
    CONFIG_EDIT_FAILED,
    CONFIG_DELETE_SUCCESS,
    CONFIG_DELETE_FAILED,
    HISTORY_SAVE_SUCCESS,
    HISTORY_SAVE_FAILED,
    HISTORY_DELETE_SUCCESS,
    HISTORY_DELETE_FAILED,
    HISTORY_EDIT_SUCCESS,
    HISTORY_EDIT_FAILED
}